"use client";

import { useEffect, useRef, useState } from "react";

type DatePickerProps = { name: string; value?: string | null; required?: boolean; label: string };
const weekdays = ["ອາທິດ", "ຈັນ", "ອັງຄານ", "ພຸດ", "ພະຫັດ", "ສຸກ", "ເສົາ"];
const toValue = (date: Date) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`;
const parse = (value?: string | null) => value && /^\d{4}-\d{2}-\d{2}$/.test(value) ? new Date(`${value}T00:00:00`) : null;
const display = (value?: string | null) => value ? value.split("-").reverse().join("/") : "DD/MM/YYYY";

export function DatePicker({ name, value, required, label }: DatePickerProps) {
  const initial = parse(value); const today = new Date(); const [selected, setSelected] = useState(value ?? ""); const [open, setOpen] = useState(false); const [month, setMonth] = useState(initial ?? today); const root = useRef<HTMLDivElement>(null);
  useEffect(() => { const close = (event: MouseEvent) => { if (root.current && !root.current.contains(event.target as Node)) setOpen(false); }; const key = (event: KeyboardEvent) => { if (event.key === "Escape") setOpen(false); }; document.addEventListener("mousedown", close); document.addEventListener("keydown", key); return () => { document.removeEventListener("mousedown", close); document.removeEventListener("keydown", key); }; }, []);
  const first = new Date(month.getFullYear(), month.getMonth(), 1); const days = new Date(month.getFullYear(), month.getMonth() + 1, 0).getDate(); const cells = [...Array(first.getDay()).fill(null), ...Array.from({ length: days }, (_, i) => new Date(month.getFullYear(), month.getMonth(), i + 1))];
  const choose = (date: Date) => { setSelected(toValue(date)); setOpen(false); };
  const move = (delta: number) => { const base = parse(selected) ?? today; const next = new Date(base); next.setDate(next.getDate() + delta); setMonth(next); setSelected(toValue(next)); };
  return <div ref={root} className="relative"><input type="hidden" name={name} value={selected}/><button type="button" onClick={() => setOpen(!open)} aria-label={`${label}${required ? " required" : ""}`} aria-haspopup="dialog" aria-expanded={open} className="w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-left text-slate-900">{display(selected)}</button>{open && <div role="dialog" aria-label={label} className="absolute z-20 mt-2 w-[min(20rem,calc(100vw-2rem))] rounded-xl border border-slate-200 bg-white p-4 shadow-lg"><div className="flex items-center justify-between"><button type="button" onClick={() => setMonth(new Date(month.getFullYear(), month.getMonth()-1,1))} aria-label="ເດືອນກ່ອນ">‹</button><strong>{month.toLocaleDateString("lo-LA", { month:"long", year:"numeric" })}</strong><button type="button" onClick={() => setMonth(new Date(month.getFullYear(), month.getMonth()+1,1))} aria-label="ເດືອນຖັດໄປ">›</button></div><div className="mt-3 grid grid-cols-7 gap-1 text-center text-xs">{weekdays.map(day=><span key={day}>{day}</span>)}{cells.map((date,index)=>date?<button key={toValue(date)} type="button" onClick={()=>choose(date)} onKeyDown={event=>{if(event.key==="ArrowLeft"){event.preventDefault();move(-1)}if(event.key==="ArrowRight"){event.preventDefault();move(1)}if(event.key==="ArrowUp"){event.preventDefault();move(-7)}if(event.key==="ArrowDown"){event.preventDefault();move(7)}}} className={`rounded-lg p-2 hover:bg-emerald-100 ${selected===toValue(date)?"bg-emerald-600 text-white":""} ${toValue(date)===toValue(today)?"ring-1 ring-emerald-500":""}`} aria-label={toValue(date)} aria-pressed={selected===toValue(date)}>{date.getDate()}</button>:<span key={`empty-${index}`}/>)}</div><div className="mt-3 flex justify-between text-sm"><button type="button" onClick={()=>choose(today)} className="text-emerald-700">ມື້ນີ້</button><button type="button" onClick={()=>{setSelected("");setOpen(false)}}>ລ້າງວັນທີ</button><button type="button" onClick={()=>setOpen(false)}>ປິດ</button></div></div>}</div>;
}
